# Change these first
owner: bandohq # Your GitHub organization or username, where this repository lives
repo: upptime-monitor # The name of this repository

sites:
  - name: Bando Site
    url: https://bando.cool
  - name: Bando API
    url: https://alpha.bando.cool/api/v1/health
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bando.cool
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bando Status
  introTitle: "Bando Status Page"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Bando
      href: https://bando.cool

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
